### ISSUE TITLE
Add board URL (.json) to the ReadMe

### ISSUE THREAD

**Issue by jkruiktech** [OnionIoT/Onion-Arduino-Boards#1]
It would be good to add the URL:
https://github.com/OnionIoT/Onion-Arduino-Boards/blob/master/IDE_Board_Manager/package_onion.io_index.json to the ReadMe

Not sure if that URL is still current, it doesn't recognise it for me (IDE v2.2.1)

**Comment by greenbreakfast** [comment]
Updated the readme to point to the relevant documentation article. This article has the URL
